"""Make TrekMap's per-day route display obvious on mobile.

This post-processes the route-day visualization block generated by
``apply_route_day_visuals.py``.  The underlying route logic is unchanged: we only
add persistent J1/J2/... badges, a compact visible legend and per-day distances.
"""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
html_path = root / "frontend" / "index.html"
html = html_path.read_text(encoding="utf-8")

match = re.search(
    r"<!-- TREKMAP_ROUTE_DAY_VISUALS_START -->.*?<!-- TREKMAP_ROUTE_DAY_VISUALS_END -->",
    html,
    flags=re.S,
)
if not match:
    raise SystemExit("La couche d'affichage des jours doit être construite avant la couche de clarté.")

block = match.group(0)

# apply_route_day_visuals.py rebuilds this whole block on every production build,
# so this marker is mainly useful to assert that the clarity pass ran.
clarity_css = r'''
/* TREKMAP_ROUTE_DAY_CLARITY_V94 */
.tm-route-day-label{background:transparent!important;border:0!important;pointer-events:none!important}
.tm-route-day-label span{
  display:grid;place-items:center;min-width:36px;height:28px;padding:0 7px;
  border:2px solid #fff;border-radius:999px;color:#fff;
  box-shadow:0 3px 12px rgba(0,0,0,.34);font:900 12px/1 system-ui,sans-serif;
  letter-spacing:.2px;text-shadow:0 1px 2px rgba(0,0,0,.28)
}
.tm-route-day-legend-title{font-size:12px!important;margin:0 0 6px!important}
.tm-route-day-rows{display:grid;gap:5px}
.tm-route-day-row{margin:0!important;padding:4px 6px;border-radius:9px;background:rgba(248,250,249,.96)}
.tm-route-day-chip{
  display:grid;place-items:center;min-width:31px;height:23px;padding:0 5px;border-radius:999px;
  color:#fff;font:900 11px/1 system-ui,sans-serif;border:2px solid #fff;
  box-shadow:0 1px 4px rgba(0,0,0,.22);flex:0 0 auto
}
.tm-route-day-row-text{font-weight:800;color:#29473a}
.tm-route-day-tooltip{font-weight:800!important}
@media(max-width:820px){
  .leaflet-top.leaflet-left .tm-route-day-legend{margin-left:52px!important;margin-top:10px!important}
  .tm-route-day-legend{
    min-width:0!important;max-width:calc(100vw - 135px)!important;max-height:none!important;
    padding:8px!important;font-size:10px!important
  }
  .tm-route-day-rows{display:flex;flex-wrap:wrap;gap:4px}
  .tm-route-day-row{gap:4px!important;padding:3px 5px!important}
  .tm-route-day-row-text{font-size:10px}
  .tm-route-day-legend small{display:none!important}
  .tm-route-day-label span{min-width:34px;height:26px;font-size:11px}
}
'''
block = block.replace("</style>", clarity_css + "\n</style>", 1)

helpers = r'''
  function segmentDistance(seg){
    const pts=cleanCoords(seg);let total=0;
    for(let i=1;i<pts.length;i++)total+=km(pts[i-1],pts[i]);
    return total;
  }
  function segmentLabelPoint(seg){
    const pts=cleanCoords(seg);if(pts.length<2)return pts[0]||null;
    const lengths=[];let total=0;
    for(let i=1;i<pts.length;i++){const d=km(pts[i-1],pts[i]);lengths.push(d);total+=d}
    if(!(total>0))return pts[Math.floor(pts.length/2)];
    const target=total/2;let walked=0;
    for(let i=1;i<pts.length;i++){
      const len=lengths[i-1];
      if(walked+len>=target){
        const f=len>0?Math.max(0,Math.min(1,(target-walked)/len)):0;
        return [pts[i-1][0]+(pts[i][0]-pts[i-1][0])*f,pts[i-1][1]+(pts[i][1]-pts[i-1][1])*f];
      }
      walked+=len;
    }
    return pts[pts.length-1];
  }
  function dayLabelIcon(day,color){
    return L.divIcon({
      className:'tm-route-day-label',
      html:`<span style="background:${color}">J${day}</span>`,
      iconSize:[42,28],iconAnchor:[21,14]
    });
  }
'''
if "function segmentLabelPoint(seg)" not in block:
    block = block.replace("  function makeLegend(segments,title){", helpers + "\n  function makeLegend(segments,title){", 1)

legend_pattern = re.compile(
    r"  function makeLegend\(segments,title\)\{.*?\n  \}\n  function protectSelectedInteraction",
    flags=re.S,
)
legend_replacement = r'''  function makeLegend(segments,title){
    const control=L.control({position:'topleft'});control.onAdd=()=>{
      const div=L.DomUtil.create('div','tm-route-day-legend');
      const rows=segments.map((seg,i)=>{
        const distance=segmentDistance(seg),color=palette[i%palette.length];
        const kmText=distance>0?` · ${distance.toFixed(1)} km`:'';
        return `<div class="tm-route-day-row"><span class="tm-route-day-chip" style="background:${color}">J${i+1}</span><span class="tm-route-day-row-text">Jour ${i+1}${kmText}</span></div>`;
      }).join('');
      div.innerHTML=`<b class="tm-route-day-legend-title">${title}</b><div class="tm-route-day-rows">${rows}</div>`+'<small><b style="display:inline;color:#166534">D</b> départ · <b style="display:inline;color:#b42318">A</b> arrivée</small>';
      L.DomEvent.disableClickPropagation(div);L.DomEvent.disableScrollPropagation(div);return div;
    };control.addTo(map);return control;
  }
  function protectSelectedInteraction'''
block, count = legend_pattern.subn(legend_replacement, block, count=1)
if count != 1:
    raise SystemExit("Impossible de remplacer la légende des jours.")

old_render = "    segments.forEach((seg,i)=>L.polyline(seg,{color:palette[i%palette.length],weight:7,opacity:.96,lineCap:'round',lineJoin:'round'}).bindTooltip(`Jour ${i+1}`,{sticky:true}).addTo(group));"
new_render = r'''    segments.forEach((seg,i)=>{
      const color=palette[i%palette.length],distance=segmentDistance(seg);
      const label=`Jour ${i+1}${distance>0?` · ${distance.toFixed(1)} km`:''}`;
      L.polyline(seg,{color,weight:7,opacity:.96,lineCap:'round',lineJoin:'round'})
        .bindTooltip(label,{sticky:true,direction:'top',className:'tm-route-day-tooltip'}).addTo(group);
      const point=segmentLabelPoint(seg);
      if(point)L.marker(point,{icon:dayLabelIcon(i+1,color),interactive:false,zIndexOffset:850}).addTo(group);
    });'''
if old_render not in block:
    raise SystemExit("Impossible de trouver le rendu des segments journaliers.")
block = block.replace(old_render, new_render, 1)

html = html[:match.start()] + block + html[match.end():]
html_path.write_text(html, encoding="utf-8")
print("TrekMap route-day clarity applied: persistent J1/J2 labels + compact legend")
